### ISSUE TITLE
possibly error in live.js (cursor instead of from)

### ISSUE THREAD

**Issue by tsol** [twilson63/aos-web#1]
https://github.com/twilson63/aos-web/blob/main/src/live.js

I've used this project as inspiation for my nuxt3 application, and once i refactored live.js to live.ts - typescript said that there is no 'cursor' parameter in results function.

I've checked documentation and it seems like proper name for the option is 'from'.

**Comment by MichaelBuhler** [comment]
@tsol Could you help us out by finding when this change occurred in the source code for `@permaweb/aoconnect`, and adding a link here? Thanks.

https://github.com/permaweb/ao/tree/main/connect

**Comment by tsol** [comment]
It looks like 'from' was proper name from the start - first commit is 22 jan already has 'from', not 'cursor':

https://github.com/permaweb/ao/commit/1bea78b4ec6bd05ad2acca23e001ad14eb35943e

**Comment by tsol** [comment]
The web-os worked by querying the endpoint with no proper cursor, hence fetching around 64KB each request (in my case). It sorted the results by DESC and took first element of the array. That caused heavy traffic and also could potentially lead to skipping some of the data.
